language: node_js
before_install: 
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - echo '##vso[task.prependpath]$(HOME)/.deno/bin/'
  - export PATH="$HOME/.deno/bin:$PATH"
install:
  - npm install eslint typescript @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-config-prettier

script:
  - deno run --allow-run --allow-write --allow-read --allow-env ./mod.ts --check