sudo: required

services:
  - docker

before_install:
  - docker build -t romduq/deno-blog .

#install:
#  - npm install eslint typescript @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-config-prettier

script:
  - docker run romduq/deno-blog run --allow-run --allow-write --allow-read --allow-env https://deno.land/x/next/mod.ts --check

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 3508c7754b9b051d2314858ea3dcb213a1d84beb
  keep_history: true
  on:
    branch: master
