version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: curl -fsSL https://deno.land/x/install/install.sh | sudo DENO_INSTALL=/usr/local sh
      - run: export PATH="$DENO_INSTALL/bin:$PATH"
      - run: npm install eslint typescript @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-config-prettier
      - run: sudo npm install -g prettier
      - run: prettier --check .
      - run: deno run --allow-run --allow-write --allow-read --allow-env mod.js --check
workflows:
  build-and-test:
    jobs:
      - build-and-test
